# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160105_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_read',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
